version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver-dockercompose
    env_file:
      - csvserver.env
    ports:
      - "9393:9300"
    
    volumes:
      - ./inputFile:/csvserver/inputdata
  
  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
