global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'csv-application'
    static_configs:
      - targets: ['98.80.69.41:9393'] # My Ec2 private IP
  - job_name: 'prometheus-self'
    static_configs:
      - targets: ['127.0.0.1:9090']
